version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: bundle install
  test:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: bundle exec rake
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
